[2024-01-20T04:11:18.541+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SpeedLayer.submit_spark_job manual__2024-01-20T04:09:51.527802+00:00 [queued]>
[2024-01-20T04:11:18.547+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SpeedLayer.submit_spark_job manual__2024-01-20T04:09:51.527802+00:00 [queued]>
[2024-01-20T04:11:18.547+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-20T04:11:18.559+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-20 04:09:51.527802+00:00
[2024-01-20T04:11:18.563+0000] {standard_task_runner.py:57} INFO - Started process 3539 to run task
[2024-01-20T04:11:18.565+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'SpeedLayer', 'submit_spark_job', 'manual__2024-01-20T04:09:51.527802+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/spark_streaming_dag.py', '--cfg-path', '/tmp/tmpojorpjbj']
[2024-01-20T04:11:18.567+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask submit_spark_job
[2024-01-20T04:11:18.605+0000] {task_command.py:415} INFO - Running <TaskInstance: SpeedLayer.submit_spark_job manual__2024-01-20T04:09:51.527802+00:00 [running]> on host 45c5bfab8aa1
[2024-01-20T04:11:18.667+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SpeedLayer' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-20T04:09:51.527802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-20T04:09:51.527802+00:00'
[2024-01-20T04:11:18.675+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-20T04:11:18.677+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --packages com.datastax.spark:spark-cassandra-connector_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1 --name arrow-spark --queue root.default /opt/***/shared_volume/spark_stream.py
[2024-01-20T04:11:18.797+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-20T04:11:20.141+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-20T04:11:20.142+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-01-20T04:11:20.143+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-01-20T04:11:20.144+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-01-20T04:11:20.144+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-01-20T04:11:20.145+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-01-20T04:11:20.146+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-01-20T04:11:20.146+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-01-20T04:11:20.147+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-01-20T04:11:20.147+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-01-20T04:11:20.148+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-20T04:11:20.175+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages com.datastax.spark:spark-cassandra-connector_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1 --name arrow-spark --queue root.default /opt/***/shared_volume/spark_stream.py. Error code is: 1.
[2024-01-20T04:11:20.180+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=SpeedLayer, task_id=submit_spark_job, execution_date=20240120T040951, start_date=20240120T041118, end_date=20240120T041120
[2024-01-20T04:11:20.207+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task submit_spark_job (Cannot execute: spark-submit --master yarn --packages com.datastax.spark:spark-cassandra-connector_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1 --name arrow-spark --queue root.default /opt/***/shared_volume/spark_stream.py. Error code is: 1.; 3539)
[2024-01-20T04:11:20.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-20T04:11:20.250+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
