[2024-01-16T22:30:30.801+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:30:28.354910+00:00 [queued]>
[2024-01-16T22:30:30.805+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:30:28.354910+00:00 [queued]>
[2024-01-16T22:30:30.806+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-16T22:30:30.815+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): coinMarket> on 2024-01-16 22:30:28.354910+00:00
[2024-01-16T22:30:30.817+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2024-01-16T22:30:30.819+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Stream_Data_1', 'coinMarket', 'manual__2024-01-16T22:30:28.354910+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpk6epxyjd']
[2024-01-16T22:30:30.820+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask coinMarket
[2024-01-16T22:30:30.896+0000] {task_command.py:415} INFO - Running <TaskInstance: Stream_Data_1.coinMarket manual__2024-01-16T22:30:28.354910+00:00 [running]> on host 99cc150d5212
[2024-01-16T22:30:31.052+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='Stream_Data_1' AIRFLOW_CTX_TASK_ID='coinMarket' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T22:30:28.354910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-16T22:30:28.354910+00:00'
[2024-01-16T22:30:31.691+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 60, in coinMarket_function
    producer = KafkaProducer(bootstrap_servers=['broker:29092'],max_bloc_ms = 5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 354, in __init__
    assert not configs, 'Unrecognized configs: %s' % (configs,)
AssertionError: Unrecognized configs: {'max_bloc_ms': 5000}
[2024-01-16T22:30:31.709+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Stream_Data_1, task_id=coinMarket, execution_date=20240116T223028, start_date=20240116T223030, end_date=20240116T223031
[2024-01-16T22:30:31.721+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task coinMarket (Unrecognized configs: {'max_bloc_ms': 5000}; 95)
[2024-01-16T22:30:31.758+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-16T22:30:31.776+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
