[2024-01-20T20:00:12.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Kafka_Producer_2.Reddit scheduled__2024-01-20T19:57:48.111996+00:00 [queued]>
[2024-01-20T20:00:12.382+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Kafka_Producer_2.Reddit scheduled__2024-01-20T19:57:48.111996+00:00 [queued]>
[2024-01-20T20:00:12.382+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-20T20:00:12.396+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Reddit> on 2024-01-20 19:57:48.111996+00:00
[2024-01-20T20:00:12.400+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2024-01-20T20:00:12.402+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Kafka_Producer_2', 'Reddit', 'scheduled__2024-01-20T19:57:48.111996+00:00', '--job-id', '1220', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream_2.py', '--cfg-path', '/tmp/tmp8gl997k2']
[2024-01-20T20:00:12.403+0000] {standard_task_runner.py:85} INFO - Job 1220: Subtask Reddit
[2024-01-20T20:00:12.444+0000] {task_command.py:415} INFO - Running <TaskInstance: Kafka_Producer_2.Reddit scheduled__2024-01-20T19:57:48.111996+00:00 [running]> on host 45c5bfab8aa1
[2024-01-20T20:00:12.507+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='Kafka_Producer_2' AIRFLOW_CTX_TASK_ID='Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-01-20T19:57:48.111996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-20T19:57:48.111996+00:00'
[2024-01-20T20:00:12.539+0000] {logging_mixin.py:151} INFO -  submission : 
[2024-01-20T20:00:13.486+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-01-20T20:00:13.489+0000] {process_utils.py:131} INFO - Sending 15 to group 354. PIDs of all processes in the group: [354]
[2024-01-20T20:00:13.491+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 354
[2024-01-20T20:00:13.491+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-20T20:00:13.492+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream_2.py", line 95, in reddit_function
    for submission in subreddit.new(limit=30):
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 47, in call
    response = request_function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request Task received SIGTERM signal
[2024-01-20T20:00:13.512+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Kafka_Producer_2, task_id=Reddit, execution_date=20240120T195748, start_date=20240120T200012, end_date=20240120T200013
[2024-01-20T20:00:13.524+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1220 for task Reddit (error with request Task received SIGTERM signal; 354)
[2024-01-20T20:00:13.544+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=354, status='terminated', exitcode=1, started='20:00:11') (354) terminated with exit code 1
[2024-01-20T20:00:13.545+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-01-20T20:00:13.564+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
