[2024-01-20T08:17:59.587+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Kafka_Producer_1.Reddit scheduled__2024-01-20T08:16:55.144173+00:00 [queued]>
[2024-01-20T08:17:59.593+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Kafka_Producer_1.Reddit scheduled__2024-01-20T08:16:55.144173+00:00 [queued]>
[2024-01-20T08:17:59.593+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-20T08:17:59.609+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Reddit> on 2024-01-20 08:16:55.144173+00:00
[2024-01-20T08:17:59.611+0000] {standard_task_runner.py:57} INFO - Started process 1239 to run task
[2024-01-20T08:17:59.615+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Kafka_Producer_1', 'Reddit', 'scheduled__2024-01-20T08:16:55.144173+00:00', '--job-id', '1040', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpj1cbqie4']
[2024-01-20T08:17:59.617+0000] {standard_task_runner.py:85} INFO - Job 1040: Subtask Reddit
[2024-01-20T08:17:59.659+0000] {task_command.py:415} INFO - Running <TaskInstance: Kafka_Producer_1.Reddit scheduled__2024-01-20T08:16:55.144173+00:00 [running]> on host 45c5bfab8aa1
[2024-01-20T08:17:59.807+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='Kafka_Producer_1' AIRFLOW_CTX_TASK_ID='Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-01-20T08:16:55.144173+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-20T08:16:55.144173+00:00'
[2024-01-20T08:17:59.883+0000] {logging_mixin.py:151} INFO -  submission : 
[2024-01-20T08:17:59.888+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'www.reddit.com\', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f121f1f87f0>: Failed to resolve \'www.reddit.com\' ([Errno -2] Name or service not known)"))')) status: GET https://oauth.reddit.com/r/Bitcoin/new
[2024-01-20T08:18:00.827+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'www.reddit.com\', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f121f1f8be0>: Failed to resolve \'www.reddit.com\' ([Errno -2] Name or service not known)"))')) status: GET https://oauth.reddit.com/r/Bitcoin/new
[2024-01-20T08:18:03.137+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_stream.py", line 95, in reddit_function
    for submission in subreddit.new(limit=30):
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 51, in _post
    response = self._requestor.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f121f21c070>: Failed to resolve 'www.reddit.com' ([Errno -2] Name or service not known)"))
[2024-01-20T08:18:03.212+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Kafka_Producer_1, task_id=Reddit, execution_date=20240120T081655, start_date=20240120T081759, end_date=20240120T081803
[2024-01-20T08:18:03.223+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1040 for task Reddit (error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f121f21c070>: Failed to resolve 'www.reddit.com' ([Errno -2] Name or service not known)")); 1239)
[2024-01-20T08:18:03.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-20T08:18:03.259+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
